partners/members/urls.py
from django.conf.urls import url, include

from partners.members.views import new, editMemberProfile, listsubscription, \
    delDataModalMemberProfile, activeDataModalMemberProfile, delConfirmeMemberProfile, activeConfirmeMemberProfile, \
    success

urlpatterns = [
    url(r'^$', new, name='new'),
    url(r'^edit/(?P<pk>\d+)$', editMemberProfile, name="edit"),
    url(r'^lista/', listsubscription, name='list'),
    url(r'^deletar/', delDataModalMemberProfile, name='delete'),
    url(r'^ativar/', activeDataModalMemberProfile, name='activate'),
    url(r'^confirmedeletar/', delConfirmeMemberProfile, name='delconfirm'),
    url(r'^confirmeativar/', activeConfirmeMemberProfile, name='activeconfirm'),
    url(r'^sucesso/', success, name='success'),
    # url(r'^dadospessoais/', include('partners.subscriptions.urls',
    #                                 namespace='subscription')),
]

partners/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from partners.core.views import home
from material.frontend import urls as frontend_urls

urlpatterns = [
    url(r'', include(frontend_urls)),
    url(r'^$', home, name='home'),
    url(r'^socio/', include('partners.members.urls',
                            namespace='memberprofiles')),
    # url(r'^inscricao/', include('partners.subscriptions.urls',
    #                             namespace='subscriptions')),

    url(r'^admin/', admin.site.urls),
]

partners/core/models.py
from django.db import models
from django.db.models import Max

def n_member():
    """
    Pega o maior número de sócio e adiciona + 1.
    :return Nº de sócio + 1:
    """
    value = Members.objects.all().aggregate(Max('member_number'))
    number = value.get('member_number__max')
    if number is None:
        number = value['member_number__max'] = 1
    else:
        number = int(value.get('member_number__max')) + 1

    return number


class Members(models.Model):
    situation_id = models.ForeignKey('Situation', verbose_name='situação')
    occupation_id = models.ForeignKey('Ocupations', verbose_name='ocupação')
    qualification_id = models.ForeignKey('Qualifications', verbose_name='qualificação')
    marital_status_id = models.ForeignKey('Marital_statuses', verbose_name='estado cívil')
    nationality_id = models.ForeignKey('Nationalities', verbose_name='nacionalidade')
    member_category_id = models.ForeignKey('Member_categories', verbose_name='categorias de membros')
    parent_level_id = models.ForeignKey('Parent_levels', verbose_name='nível parental')
    collector_id = models.ForeignKey('Colectors', verbose_name='coletores')
    # anchor_member_id = models.ForeignKey('Anchor_member', verbose_name='coletores')
    first_name = models.CharField('Nome', max_length=64)
    last_name = models.CharField('Apelido', max_length=64)
    member_number = models.IntegerField('nº do sócio', default=n_member)
    sex = models.BooleanField('sexo', default=True)
    birthdate = models.DateField('data nascimento', blank=True)
    crm_number = models.CharField('compania', max_length=64, blank=True)
    lock_renumbering = models.BooleanField('lock_renumbering', default=True)

    class Meta:
        ordering = ["member_number"]
        verbose_name = 'membro'
        verbose_name_plural = 'membros'

    def __str__(self):
        return self.name


class Situation(models.Model):
    description = models.TextField('descrição', max_length=128, blank=True)
    active = models.BooleanField('ativo', blank=True)
    free_clubfree = models.BooleanField('livre de quotas', blank=True)
    free_subscription = models.BooleanField('livre de subscrição', blank=True)
    inhibited_clubfree = models.BooleanField('inibido de quotas', blank=True)
    inhibited_subscription = models.BooleanField('inibido de subscrição', blank=True)
    inhibited_ticket = models.BooleanField('inibido de ticket', blank=True)
    inhibited_season_ticket = models.BooleanField('inibido de temporada', blank=True)

    class Meta:
        verbose_name = 'situação'
        verbose_name_plural = 'situações'


class Ocupations(models.Model):
    description = models.TextField('descrição', max_length=128, blank=True)

    class Meta:
        verbose_name = 'ocupação'
        verbose_name_plural = 'ocupações'

    def __str__(self):
        return self.description


class Qualifications(models.Model):
    description = models.TextField('descrição', max_length=128, blank=True)

    class Meta:
        verbose_name = 'qualificação'
        verbose_name_plural = 'qualificações'

    def __str__(self):
        return self.description


class Marital_statuses(models.Model):
    description = models.TextField('descrição', max_length=128, blank=True)

    class Meta:
        verbose_name = 'estado cívil'
        # verbose_name_plural = 'qualificações'

    def __str__(self):
        return self.description


class Nationalities(models.Model):
    country_id = models.ForeignKey('Countries', verbose_name='paises')
    first_denomination = models.TextField('1ª denominação', max_length=64, blank=True)
    second_denomination = models.TextField('2ª denominação', max_length=64, blank=True)

    class Meta:
        verbose_name = 'nacionalidades'
        # verbose_name_plural = 'qualificações'

    def __str__(self):
        return self.first_denomination


class Countries(models.Model):
    description = models.TextField('descrição', max_length=128, blank=True)

    class Meta:
        verbose_name = 'país'
        verbose_name_plural = 'paises'

    def __str__(self):
        return self.description


class Country_zones(models.Model):
    description = models.TextField('descrição', max_length=128, blank=True)

    class Meta:
        verbose_name = 'zona do país'
        verbose_name_plural = 'zonas do país'

    def __str__(self):
        return self.description


class Member_categories(models.Model):
    description = models.TextField('descrição', max_length=128, blank=True)
    # relation_profile_id = models.ForeignKey('Relations_profiles', verbose_name='nacionalidade')
    next_category_id = models.IntegerField('próxima categoria', blank=True)
    free_clubfee = models.BooleanField(default=True)
    free_special_clubfee = models.BooleanField(default=True)
    right_to_vote = models.BooleanField(default=True)
    number_votes = models.IntegerField(blank=True)
    relation_years = models.IntegerField(blank=True)
    automatic_approval = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'categoria de membro'
        verbose_name_plural = 'categorias de membros'

    def __str__(self):
        return self.description


class Parent_levels(models.Model):
    description = models.TextField('Nível parental', max_length=128, blank=True)

    # class Meta:
    #     verbose_name = 'país'
    #     verbose_name_plural = 'paises'

    def __str__(self):
        return self.description


class Colectors(models.Model):
    colector_group_id = models.ForeignKey('Colector_groups')
    description = models.TextField('descrição', max_length=128, blank=True)

    class Meta:
        verbose_name = 'cobrador'
        verbose_name_plural = 'cobradores'

    def __str__(self):
        return self.description


class Colector_groups(models.Model):
    collecting_type_id = models.ForeignKey('Colecting_types')
    description = models.TextField('descrição', max_length=128, blank=True)

    class Meta:
        verbose_name = 'grupo cobrador'
        verbose_name_plural = 'grupos cobradores'

    def __str__(self):
        return self.description


class Colecting_types(models.Model):
    description = models.TextField('descrição', max_length=128, blank=True)

    class Meta:
        verbose_name = 'tipo de cobrança'
        verbose_name_plural = 'tipos de cobrança'

    def __str__(self):
        return self.description


class MemberContact(models.Model):
    member_id = models.ForeignKey('Members', verbose_name='nº de membro')
    email = models.EmailField('email', max_length=128, blank=True)
    telephone_1 = models.CharField('telemóvel', max_length=32, blank=True)
    telephone_2 = models.CharField('telefone', max_length=32, blank=True)

    class Meta:
        verbose_name = 'membro contato'
        verbose_name_plural = 'membro contatos'

    def __str__(self):
        return self.email


class MemberAddress(models.Model):
    member_id = models.ForeignKey('Members', verbose_name='nº de membro')
    # address_type_id = models.ForeignKey()
    country_id = models.ForeignKey('Countries')
    zone_id = models.ForeignKey('Country_zones')
    city = models.CharField('cicade', max_length=128, blank=True)
    address = models.CharField('morada', max_length=128, blank=True)
    postcode = models.CharField('código postal', max_length=32, blank=True)

    class Meta:
        verbose_name = 'endereço'
        verbose_name_plural = 'endereços'

    def __str__(self):
        return self.address


class Member_documents(models.Model):
    member_id = models.ForeignKey('Members', verbose_name='nº de membro')
    document_id = models.ForeignKey('Documents', verbose_name='documento', blank=True)
    document_value = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name = 'documento'
        verbose_name_plural = 'documentos sócio'

    def __str__(self):
        return self.document_id


class Profession_members(models.Model):
    member_id = models.ForeignKey('Members', verbose_name='nº de membro')
    description = models.TextField('descrição', max_length=128, blank=True)
    profession_situation_id = models.ForeignKey('Profession_situations', verbose_name='situação profissional')
    company = models.CharField('companhia', max_length=68, blank=True)

    class Meta:
        verbose_name = 'situação profissional'
        # verbose_name_plural = 'ocupações'

    def __str__(self):
        return self.description


class Profession_situations(models.Model):
    description = models.TextField('descrição', max_length=128, blank=True)

    class Meta:
        verbose_name = 'situação profissional'
        # verbose_name_plural = 'tipos de cobrança'

    def __str__(self):
        return self.description


class Documents(models.Model):
    description = models.TextField('descrição', max_length=128, blank=True)

    class Meta:
        verbose_name = 'documento'
        verbose_name_plural = 'documentos'

partners/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'index.html')

partners/core/templates/base.html
{#{% extends 'material/base_form.html' %}#}
{% load static %}
    {% include 'material/includes/material_css.html' %}
    <script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
     {% load material_form %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Admin V1.0">
    <meta name="author" content="Adriano Regis">
    <meta name="keyword" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>

    <!-- start: Css -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- plugins -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/plugins/font-awesome.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/plugins/simple-line-icons.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/plugins/animate.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/plugins/fullcalendar.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/plugins/custom/custom.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- end: Css -->
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
{% include 'nav_top.html' only %}
{% block nav %}
    {% include 'nav.html' only %}
{% endblock nav %}
<body>
<div>
    {% block content %}
    {% endblock content %}

    {% block perfil %}
    {% endblock perfil %}
</div>
</body>
</html>

<!-- start: Javascript -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.ui.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>


<!-- plugins -->
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/jquery.nicescroll.js' %}"></script>
<script src="{% static 'js/plugins/fullcalendar.min.js' %}"></script>


<script src="{% static 'js/plugins/jquery.vmap.min.js' %}"></script>
<script src="{% static 'js/plugins/maps/jquery.vmap.world.js' %}"></script>
<script src="{% static 'js/plugins/jquery.vmap.sampledata.js' %}"></script>
<script src="{% static 'js/plugins/chart.min.js' %}"></script>


{#<!-- plugins datatables-->#}
{#<script src="{% static 'js/plugins/jquery.datatables.min.js' %}"></script>#}
{#<script src="{% static 'js/plugins/datatables.bootstrap.min.js' %}"></script>#}


<!-- custom -->
<script src="{% static 'js/main.js' %}"></script>

{% block javascript %}
{% endblock javascript %}
<script type="text/javascript">
    $(document).ready(function () {
        console.log("ready atleta!");
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    });
</script>

partners/core/templates/colunm_button.html
<div class="form-group">
    <div class="col-sm-5">
        {% if isDefault != 1 %}
            {% if saveNew == 1 %}
                <input type="button" id="saveAndNew" class="btn btn-primary"
                       name="SaveAndNew"
                       value="Guardar & Novo" style="float:left;margin-right:7px;"/>
            {% endif %}
            {% if bEdit %}
                <input type="button" id="bEdit" class="btn btn-primary" name="Save"
                       value="Editar"
                       style="float:left;"/>
            {% else %}
                <input type="button" id="save" class="btn btn-primary" name="Save"
                       value="Guardar"
                       style="float:left;"/>
            {% endif %}
            <div class="cancel"><span class="text_small"></span>
                <input type="button" id="b_cancelar" class="btn btn-default"
                       name="Cancelar"
                       value="Cancelar"/>
            </div>
        {% else %}
            <div class="cancel">
                <input type="button" id="b_cancelar" class="btn_cancelar"
                       name="Cancelar"
                       value="Voltar"/>
            </div>
        {% endif %}
    </div>
</div>

partners/core/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block nav %}
    <div class="header-frame row">
        {% include 'nav.html' only %}
    </div>
{% endblock nav %}

{% block content %}
    <link type="text/css" rel="stylesheet" href="{% static 'js/plugins/dataTables/dataTables.bootstrap.css' %}">
    <!-- start: Content -->
    <div id="content">
        <div class="panel box-shadow-none content-header">
            <div class="panel-body">
                <div class="col-md-12">
                    <h3 class="animated fadeInLeft">Sócio</h3>
                    <p class="animated fadeInDown">
                        <a href="#">Movimento Associativo</a> <span class="fa-angle-right fa"></span>
                        Sócio
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-12 top-20">
            <div class="col-md-12 ">
                <div class="panel form_id">
                    <div class="panel-heading"><h3>Lista de sócios</h3>
                        {% if data != 0 %}
                            {% if tamLista != 0 %}
                                <div class="dropdown">
                                    <input id="criar_member" class="btn btn-primary" type="button"
                                           value="Inscrição"/>
                                    <a href="#" data-toggle="dropdown" class="btn btn-default ">Mais<b
                                            class="caret"></b></a>
                                    <ul class="dropdown-menu more" role="menu" aria-labelledby="dLabel">
                                    <li><a href="#" data-toggle="modal" data-target="#ativarModal_member"
                                           class="men_apagar">{% trans 'Ativar' %}</a></li>
                                    <li><a href="#" data-toggle="modal" data-target="#apagarModal_member"
                                           class="men_apagar">{% trans 'Desativar' %}</a></li>
                                    </ul>
                                </div>
                            {% endif %}
                            {% if tamLista == 0 %}
                                <div class="no_content">
                                    <input id="criar_member" class="btn btn-primary" type="button"
                                           value="Novo"/>
                                    <img src="{% static 'img/empty_arrow_h.png' %}">
                                    <p>Clique para criar um registo.</p>
                                </div>
                            {% else %}
                                </div>
                                <div class="panel-body">
                                    <div class="responsive-table">
                                        <table id="datatables-example" class="table table-striped table-bordered"
                                               width="100%"
                                               cellspacing="0">
                                            <thead>
                                            <tr>
                                                <th width="38px;"><input type="checkbox" class="checkAll"></th>
                                                <th>"Nº do sócio</th>
                                                <th>Nome</th>
                                                <th>Ativo</th>
                                                <th>Categoria</th>
                                                <th>Última quota paga</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for member in list %}
{#                                                {% if member.situation == True %}#}
                                                    <tr>
                                                        <td><input type="checkbox" value="{{ member.pk }}"
                                                                   class="checkable">
                                                        </td>
                                                        <td><a style="color: #337ab7" href="#"
                                                               class="edit_member navbar-link"
                                                               data-toggle="modal"
                                                               name="{{ member.pk }}">{{ member.member_number }}</a>
                                                        </td>
                                                        <td>{{ member.name }}</td>
                                                        <td>{{ member.situation }}</td>
{#                                                        <td>#}
{#                                                            <div style="color: #1B5E20"#}
{#                                                                 class="glyphicon glyphicon-ok">#}
{#                                                            </div>#}
{#                                                        </td>#}
                                                        <td>{{ member.category }}</td>
                                                        <td>{{ member.last_quota }}</td>
                                                    </tr>
{#                                                {% else %}#}
{#                                                    <tr style="color: #c0c0c0">#}
{#                                                        <td><input type="checkbox" value="{{ member.pk }}"#}
{#                                                                   class="checkable">#}
{#                                                        </td>#}
{#                                                        <td><a style="color: #c0c0c0"#}
{#                                                               class="navbar-link"#}
{#                                                               data-toggle="modal"#}
{#                                                               name="{{ member.pk }}">{{ member.member_number }}</a>#}
{#                                                        </td>#}
{#                                                        <td>{{ member.name }}</td>#}
{#                                                        <td>{{ member.situation }}</td>#}
{#                                                        <td>#}
{#                                                            <div style="color: #cc1111"#}
{#                                                                 class="glyphicon glyphicon-remove"></div>#}
{#                                                        </td>#}
{#                                                        <td>{{ member.category }}</td>#}
{#                                                        <td>{{ member.last_quota }}</td>#}
{##}
{#                                                    </tr>#}
{#                                                {% endif %}#}
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            {% endif %}
                        {% else %}
                            <div class="no_content">
                                <input id="criar_avaliacao" class="btn btn-primary" type="button"
                                       value="Novo" disabled/>
                                <img src="{% static 'img/empty_arrow_h.png' %}">
                                <p>Habilitado após ser adicionado um Plano de mensalidade.</p>
                            </div>
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="apagarModal_member" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true"></div>
    <div class="modal fade" id="ativarModal_member" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true"></div>
    <!-- end: content -->

    <!-- start: Javascript -->
    {#    <script src="{% static 'js/jquery.min.js' %}"></script>#}
    {#    <script src="{% static 'js/jquery.ui.min.js' %}"></script>#}
    {#    <script src="{% static 'js/bootstrap.min.js' %}"></script>#}

    <!-- plugins -->
    {#    <script src="{% static 'js/plugins/moment.min.js' %}"></script>#}

    <!-- end: Javascript -->


{% endblock content %}

{% block javascript %}

    <script src="{% static 'js/plugins/jquery.datatables.min.js' %}"></script>
    <script src="{% static 'js/plugins/datatables.bootstrap.min.js' %}"></script>
    {#    <script src="{% static 'js/plugins/jquery.nicescroll.js' %}"></script>#}

    <!-- custom -->
    {#    <script src="{% static 'js/main.js' %}"></script>#}
    <script type="text/javascript">

        $(document).ready(function () {
            console.log("ready member!");
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            $('#datatables-example').DataTable({
                "oLanguage": {
                    "sUrl": "/static/dataTables/lang/pt-pt.txt"
                },
                "sScrollY": "710px",
                "bScrollCollapse": true,
                "bStateSave": true,
                "aoColumnDefs": [
                    {
                        'bSortable': true,
                        'aTargets': [0]
                    }
                ]

            });

            $('.checkAll').click(function () {
                console.log("checkAll!");
                $('input:checkbox.checkable').prop('checked', this.checked);
            });

            $("#criar_member").click(function () {
                var csrftoken = getCookie('csrftoken');
                $.ajax({
                    url: "{% url 'memberprofiles:new'%}",
                    {#                                    url: "/socio/form",#}
                    type: 'GET',
                    data: {'value': ""},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        console.log("index member!");
                        {#                      console.log(data);#}
                        $(".form_id").html(data);
                    }
                });
            });

            $(".edit_member").click(function () {
                var csrftoken = getCookie('csrftoken');
                var idUserProfile = $(this).attr("name");

                $.ajax({
                    url: '/socio/edit/' + idUserProfile,
                    type: 'GET',
                    data: {},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        $(".form_id").html(data);
                    }
                });

            });

            $("#apagarModal_member").on('show.bs.modal', function (event) {
                console.log("Apagar!");
                var vals = [];
                $('input:checked.checkable').each(function () {
                    var valor = $(this).val();
                    if (valor != undefined) {
                        vals.push(valor);
                    }
                });
                var target = "{%url 'memberprofiles:delete'%}"
                var csrftoken = getCookie('csrftoken');
                $.ajax({
                    type: "POST",
                    url: target,
                    data: {valores: vals},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        $('#apagarModal_member').html(data);
                    },
                    error: function (rs, e) {

                    }
                });
            });

            $("#ativarModal_member").on('show.bs.modal', function (event) {
                console.log("Ativar xxx!");
                var vals = [];
                $('input:checked.checkable').each(function () {
                    var valor = $(this).val();
                    if (valor != undefined) {
                        vals.push(valor);
                    }
                });
                var target = "{%url 'memberprofiles:activate'%}"
                var csrftoken = getCookie('csrftoken');
                $.ajax({
                    type: "POST",
                    url: target,
                    data: {valores: vals},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        $('#ativarModal_member').html(data);
                    },
                    error: function (rs, e) {

                    }
                });
            });

        });
    </script>
{% endblock javascript %}

partners/core/templates/pagina_nao_autorizada.html
{#{% extends "base.html" %}#}
{% load static %}
{% load i18n %}


{% block content %}
    <!-- start: content -->
    <div class="col-md-12 text-center">
        <div class="alert-access-denied">
            <a href="#" onClick="history.go(-1)">
                <img src="{% static 'img/lock.png' %}">
            </a>
            <div>
                <h3><strong>Página não autorizada!</strong></h3>
                <p>Não está autorizado a aceder a esta página.<br/>Por favor contacte o administrador.
                    <br/><a href="#" onClick="history.go(-1)">Voltar à página anterior.</a></p>
            </div>
        </div>
    </div>
    <!-- end: content -->
{% endblock %}

partners/core/templates/success.html
<form method="get" action="'{{ path }}'" class="form-horizontal">
    {% csrf_token %}
    <div class="col-md-8">
        <div class="panel form-element-padding">
{#            <div class="panel-heading">#}
{#                <h4>Sucesso!</h4>#}
{#            </div>#}
            <div class="panel-body" style="padding-bottom:30px;">
                <div class="form-group">
                    <div class="col-sm-5">

                        <input type="submit" id="save" class="btn btn-primary" name="Save" value="Ok"
                               style="float:left;"/>
                    </div>
                </div>
                    {% if messages %}
                        <div class="span12">
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}">
                                    <h3>{{ message|safe }}</h3>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
            </div>
        </div>
    </div>
</form>