partners/members/urls.py
from django.conf.urls import url, include

from partners.members.views import new, editMemberProfile, listsubscription, \
    delDataModalMemberProfile, activeDataModalMemberProfile, delConfirmeMemberProfile, activeConfirmeMemberProfile, \
    success

urlpatterns = [
    url(r'^$', new, name='new'),
    url(r'^edit/(?P<pk>\d+)$', editMemberProfile, name="edit"),
    url(r'^lista/', listsubscription, name='list'),
    url(r'^deletar/', delDataModalMemberProfile, name='delete'),
    url(r'^ativar/', activeDataModalMemberProfile, name='activate'),
    url(r'^confirmedeletar/', delConfirmeMemberProfile, name='delconfirm'),
    url(r'^confirmeativar/', activeConfirmeMemberProfile, name='activeconfirm'),
    url(r'^sucesso/', success, name='success'),
    # url(r'^dadospessoais/', include('partners.subscriptions.urls',
    #                                 namespace='subscription')),
]

partners/subscriptions/urls.py
from django.conf.urls import url


from partners.subscriptions.views import new, success, new_quick

urlpatterns = [
    url(r'^$', new, name='new'),
    url(r'^inscricaorapida/', new_quick, name='quickregister'),
    # url(r'^edit/(?P<pk>\d+)$', editSubscription, name="edit"),
    # # url(r'^lista/', listsubscription, name='list'),
    # url(r'^deletar/', delDataModalSubscription, name='delete'),
    # url(r'^ativar/', activeDataModalSubscription, name='activate'),
    # url(r'^confirmedeletar/', delConfirmeSubscription, name='delconfirm'),
    # url(r'^confirmeativar/', activeConfirmeSubscription, name='activeconfirm'),
    url(r'^sucesso/', success, name='success'),
]

partners/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from partners.core.views import home
from material.frontend import urls as frontend_urls

urlpatterns = [
    url(r'', include(frontend_urls)),
    url(r'^$', home, name='home'),
    url(r'^socio/', include('partners.members.urls',
                            namespace='memberprofiles')),
    # url(r'^inscricao/', include('partners.subscriptions.urls',
    #                             namespace='subscriptions')),

    url(r'^admin/', admin.site.urls),
]

partners/subscriptions/models.py
from django.db import models

# Create your models here.

partners/subscriptions/forms.py
from django import forms
from django.forms import ModelForm

from partners.members.models import MemberProfile, n_member

BOOL_CHOICES = ((True, 'Sim'), (False, 'Não'))

default = ''
CC = 'Cartão do Cidadão'
BI = 'Bilhete de Identidade'
NIF = 'Número de Identidade Fiscal'
DOC = (
    (default, '---'),
    (CC, 'Cartão do Cidadão'),
    (BI, 'Bilhete de Identidade'),
    (NIF, 'Número de Identidade Fiscal')
)

default = ''
A = 'Ativo'
DFP = 'Demitido falta pagamento'
F = 'Falecimento'
S = 'Suspenso'
SITUACAO = (
    (default, '---'),
    (A, 'Ativo'),
    (DFP, 'Demitido falta pagamento'),
    (F, 'Falecimento'),
    (S, 'Suspenso')
)

default = ''
MALE = 'Masculino'
FEMALE = 'Feminino'
SEX = (
    ('', '---'),
    (MALE, 'Masculino'),
    (FEMALE, 'Feminino'),
)

default = ''
BA = 'Bancada'
EF = 'Efetivo'
IN = 'infantil'
SEN = 'Sénior'
CATEGORY = (
    (default, '---'),
    (BA, 'Bancada'),
    (EF, 'Efetivo'),
    (IN, 'infantil'),
    (SEN, 'Sénior'),
)

default = ''
SO = 'Sócio'
AD = 'Adpto'
CLI = 'Cliente'
FUN = 'Funcionário'
AT = 'Atleta'
SE = 'Seccionista'
PERFIL = (
    (default, '---'),
    (SO, 'Sócio'),
    (AD, 'Adpto'),
    (CLI, 'Cliente'),
    (FUN, 'Funcionário'),
    (AT, 'Atleta'),
    (SE, 'Seccionista')
)

default = ''
PT = 'Portuguesa'
BR = 'Brasileira'
MZ = 'Moçanbicana'
OUT = 'Outras Nacionalidades'

NACIONALIDADE = (
    (default, '---'),
    (PT, 'Portuguesa'),
    (BR, 'Brasileira'),
    (MZ, 'Moçanbicana'),
    (OUT, 'Outras Nacionalidades'),
)

default = ''
LiS = 'Lisboa'
POR = 'Porto'
OUT = 'Outras Naturalidades'

NATURALIDADE = (
    (default, '---'),
    (LiS, 'Lisboa'),
    (POR, 'Porto'),
    (OUT, 'Outras Naturalidades')
)

default = ''
PRI = '1º Ciclo'
SEC = '2º Ciclo'
TER = '3º Ciclo'
LI = 'Licenciado'
DO = 'Doutorado'

HABILITACOES = (
    (default, '---'),
    (PRI, '1º Ciclo'),
    (SEC, '2º Ciclo'),
    (TER, '3º Ciclo'),
    (LI, 'Licenciado'),
    (DO, 'Doutorado')
)

default = ''
EE = 'Empregado Escritório'
TH = 'Técnico Hardware'
PRG = 'Programador'
PRO = 'Professor'
ADV = 'Advogado'

PROFISSOES = (
    (default, '---'),
    (EE, 'Empregado Escritório'),
    (TH, 'Técnico Hardware'),
    (PRG, 'Programador'),
    (PRO, 'Professor'),
    (ADV, 'Advogado')
)

default = ''
ECO = 'Empregado por conta de outrém'
ECP = 'Empregado por conta própria'
PL = 'Profissional Liberal'
DES = 'Desempregado'

SIT_PROFISSIONAL = (
    (default, '---'),
    (ECO, 'Empregado por conta de outrém'),
    (ECP, 'Empregado por conta própria'),
    (PL, 'Profissional Liberal'),
    (DES, 'Desempregado'),
)

default = ''
C = 'Casado'
S = 'Solteiro'
D = 'Divorciado'
V = 'Viuvo'

ESTADO_CIVIL = (
    (default, '---'),
    (C, 'Casado'),
    (S, 'Solteiro'),
    (D, 'Divorciado'),
    (V, 'Viuvo'),
)


class SubscriptionForm(ModelForm):
    # id = forms.CharField(label='Número do Sócio', required=True, widget=forms.TextInput(
    #     attrs={'placeholder': 'Nº', 'class': 'form-control', 'readonly':'readonly'}))
    member_number = forms.IntegerField(initial=n_member, label='Nº Sócio', required=False,
                                       widget=forms.TextInput(
                                           attrs={'placeholder': 'Nº', 'class': 'form-control',
                                                  'readonly': 'readonly'}))

    name = forms.CharField(label='Nome', required=True, widget=forms.TextInput(
        attrs={'placeholder': 'nome', 'class': 'form-control'}))

    document_type = forms.ChoiceField(DOC, label='Documento Idendificação', required=False,
                                      widget=forms.Select(attrs={'placeholder': '--',
                                                                 'class': 'form-control input-sm medio required_form'})
                                      )
    admission_date = forms.DateField(label='Data de emissão', required=False,
                                     widget=forms.DateInput(
                                         attrs={'placeholder': 'dd/mm/yyyy', 'class': 'form-control date mask-date',
                                                ' data-provide': 'datepicker',
                                                'data-date-format': 'dd/mm/yyyy'}))

    doc_number = forms.CharField(label='Número do Documento', required=False, widget=forms.TextInput(
        attrs={'placeholder': 'Nº', 'class': 'form-control'}))

    doc_emmission = forms.CharField(label='Local de Emissão', required=False, widget=forms.TextInput(
        attrs={'placeholder': 'local', 'class': 'form-control'}))

    situation = forms.ChoiceField(SITUACAO, label='Situação', required=False, initial=True,
                                  widget=forms.Select(attrs={'placeholder': '--',
                                                             'class': 'form-control input-sm medio required_form'})
                                  )

    last_quota = forms.DateField(label='Última quota paga', required=False,
                                 widget=forms.DateInput(
                                     attrs={'placeholder': 'dd/mm/yyyy', 'class': 'form-control date mask-date',
                                            ' data-provide': 'datepicker',
                                            'data-date-format': 'dd/mm/yyyy'}))

    # category = forms.CharField(label='Categoria', required=True, widget=forms.TextInput(
    #     attrs={'placeholder': 'categoria', 'class': 'form-control'}))

    category = forms.ChoiceField(CATEGORY, label='Categoria', required=False,
                                 widget=forms.Select(attrs={'placeholder': '--',
                                                            'class': 'form-control input-sm medio required_form'})
                                 )

    profile = forms.ChoiceField(PERFIL, label='Perfil', required=False,
                                widget=forms.Select(attrs={'placeholder': '--',
                                                           'class': 'form-control input-sm medio required_form'})
                                )

    sex = forms.ChoiceField(SEX, label='Sexo', required=False, initial=True,
                            widget=forms.Select(attrs={'placeholder': '--',
                                                       'class': 'form-control input-sm medio required_form'})
                            )

    birthdate = forms.DateField(label='Data de Nascimento', required=False,
                                widget=forms.DateInput(
                                    attrs={'placeholder': 'dd/mm/yyyy', 'class': 'form-control date mask-date',
                                           ' data-provide': 'datepicker',
                                           'data-date-format': 'dd/mm/yyyy'}))

    # nationality = forms.CharField(label='Nacionalidade', required=False, widget=forms.TextInput(
    #     attrs={'placeholder': '', 'class': 'form-control'}))
    nationality = forms.ChoiceField(NACIONALIDADE, label='Nacionalidade', required=False,
                                    widget=forms.Select(attrs={'placeholder': '--',
                                                               'class': 'form-control input-sm medio required_form'})
                                    )

    # naturalness = forms.CharField(label='Naturalidade', required=False, widget=forms.TextInput(
    #     attrs={'placeholder': '', 'class': 'form-control'}))
    naturalness = forms.ChoiceField(NATURALIDADE, label='Naturalidade', required=False,
                                    widget=forms.Select(attrs={'placeholder': '--',
                                                               'class': 'form-control input-sm medio required_form'})
                                    )

    # marital_status = forms.CharField(label='Estado Civil', required=False, widget=forms.TextInput(
    #     attrs={'placeholder': '', 'class': 'form-control'}))
    marital_status = forms.ChoiceField(ESTADO_CIVIL, label='Estado Civil', required=False,
                                       widget=forms.Select(attrs={'placeholder': '--',
                                                                  'class': 'form-control input-sm medio required_form'})
                                       )

    # qualifications = forms.CharField(label='Habilitações', required=False, widget=forms.TextInput(
    #     attrs={'placeholder': '', 'class': 'form-control'}))
    qualifications = forms.ChoiceField(HABILITACOES, label='Habilitações', required=False,
                                       widget=forms.Select(attrs={'placeholder': '--',
                                                                  'class': 'form-control input-sm medio required_form'})
                                       )

    # profession = forms.CharField(label='Profissão', required=False, widget=forms.TextInput(
    #     attrs={'placeholder': '', 'class': 'form-control'}))

    profession = forms.ChoiceField(PROFISSOES, label='Profissão', required=False,
                                   widget=forms.Select(attrs={'placeholder': '--',
                                                              'class': 'form-control input-sm medio required_form'})
                                   )

    # professional_situation = forms.CharField(label='Situação Profissional', required=False, widget=forms.TextInput(
    #     attrs={'placeholder': '', 'class': 'form-control'}))
    professional_situation = forms.ChoiceField(SIT_PROFISSIONAL, label='Situação Profissional', required=False,
                                               widget=forms.Select(attrs={'placeholder': '--',
                                                                          'class': 'form-control input-sm medio required_form'})
                                               )

    father = forms.CharField(label='Nome do Pai', required=False, widget=forms.TextInput(
        attrs={'placeholder': '', 'class': 'form-control'}))

partners/subscriptions/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import resolve_url as r

from partners.members.models import MemberProfile
from partners.subscriptions.forms import SubscriptionForm


def new(request):
    if request.method == 'POST':
        print('NEW POST')
        return create(request)

    return empty_form(request)


def empty_form(request):
    return render(request, 'subscriptions/add.html',
                  {'form': SubscriptionForm()})


def create(request):
    form = SubscriptionForm(request.POST or None)
    print('FORM: ', request.POST)
    if not (form.is_valid()):
        return render(request, 'subscriptions/add_return.html', locals())
    else:
        MemberProfile.objects.create(**form.cleaned_data)

        return HttpResponseRedirect(r('subscriptions:success'))


def new_quick(request):
    if request.method == 'POST':
        print('NEW POST Rapido')
        return create_quick(request)

    return empty_form_quick(request)


def empty_form_quick(request):
    return render(request, 'subscriptions/add_quick_registration.html',
                  {'form': SubscriptionForm()})


def create_quick(request):
    form = SubscriptionForm(request.POST or None)
    if not (form.is_valid()):
        return render(request, 'subscriptions/add_quick_registration_return.html', locals())
    else:
        member = MemberProfile(name=form.cleaned_data['name'],
                               document_type=form.cleaned_data['document_type'],
                               doc_number=form.cleaned_data['doc_number'],
                               sex=form.cleaned_data['sex'],
                               birthdate=form.cleaned_data['birthdate'],
                               category=form.cleaned_data['category'],
                               email=form.cleaned_data['email'],
                               telephone_1=form.cleaned_data['telephone_1'],
                               telephone_2=form.cleaned_data['telephone_2'])
        member.save()

        return HttpResponseRedirect(r('subscriptions:success'))


def success(request):
    return render(request, 'subscriptions/subscription_success.html')

partners/subscriptions/templates/subscriptions/ativar_modal.html
{% load i18n %}

<div class="col-md-12 modal-example">
    <div class="col-md-12">
        <div class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Grupos de Permissões</h4>
                    </div>
                    <div class="modal-body">
                        {% if users %}
                            <p>{% trans "Deseja mesmo ativar o(s) sócio(s):" %}</p>
                            <ul>
                                {% for user in users %}
                                    <li class="values_activeted"
                                        value="{{ user.pk }}">{{ user.name }}</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>{% trans "Não selecionou nenhuma sócio!" %}</p>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Voltar
                                </button>
                            </div>
                        {% endif %}
                    </div>
                    {% if users %}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar
                            </button>
                            <button id="btn_ativarSim" data-dismiss="modal" type="button" class="btn btn-primary">Sim
                            </button>
                        </div>
                    {% endif %}
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $('#btn_ativarSim').on("click", function () {
        console.log("ATIVA!");
            var ids = [];
            console.log(ids)
            $('.values_activeted').each(function () {
                ids.push($(this).val());
            });

            var target = "{%url 'memberprofiles:activeconfirm'%}"
            var csrftoken = getCookie('csrftoken');

            $('#ativarModal_user').modal('hide');

            $.ajax({
                type: "POST",
                url: target,
                data: {valores_list: ids},
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                },
                success: function (data) {
                    location.reload(true);//refresh na página
                    {#          		$('.form_id').html(data);#}
                    $('div').removeClass("modal-backdrop fade in");
                },
                error: function (rs, e) {

                }
            });
        });
    });


</script>

partners/subscriptions/templates/subscriptions/desativar_modal.html
{% load i18n %}

<div class="col-md-12 modal-example">
    <div class="col-md-12">
        <div class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Grupos de Permissões</h4>
                    </div>
                    <div class="modal-body">
                        {% if users %}
                            <p>{% trans "Deseja mesmo apagar o(s) sócio(s):" %}</p>
                            <ul>
                                {% for user in users %}
                                    <li class="values_delete"
                                        value="{{ user.pk }}">{{ user.name }}</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>{% trans "Não selecionou nenhuma sócio!" %}</p>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Voltar
                                </button>
                            </div>
                        {% endif %}
                    </div>
                    {% if users %}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar
                            </button>
                            <button id="btn_apagarSim" data-dismiss="modal" type="button" class="btn btn-primary">Sim
                            </button>
                        </div>
                    {% endif %}
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        console.log("REMOVE!");
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $('#btn_apagarSim').on("click", function () {

            var ids = new Array();
            console.log(ids)
            $('.values_delete').each(function () {
                ids.push($(this).val());
            });

            var target = "{%url 'memberprofiles:delconfirm'%}"
            var csrftoken = getCookie('csrftoken');

            $('#apagarModal_user').modal('hide');

            $.ajax({
                type: "POST",
                url: target,
                data: {valores_list: ids},
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                },
                success: function (data) {
                    location.reload(true);//refresh na página
                    {#          		$('.form_id').html(data);#}
                    $('div').removeClass("modal-backdrop fade in");
                },
                error: function (rs, e) {

                }
            });
        });
    });


</script>

partners/subscriptions/templates/subscriptions/nav_member.html
{% load static %}

<!-- start:Left Menu -->
<div id="left-menu">
    <div class="sub-left-menu scroll" tabindex="5000" style="overflow: hidden; outline: none;">
        <ul class="nav nav-list">
            <li>
                <div><img style="margin-top: -2%;" class="logo-img" href="{% static 'img/porto.png' %}" height="100px" width="100px"></div>
            </li>
{#            <li class="time">#}
                {#                    <h1 class="animated fadeInLeft">21:00</h1>#}
                {#                    <p class="animated fadeInDown">Sat,October 1st 2029</p>#}
{#            </li>#}
            {#                {% if not user.is_authenticated %}#}
            {#                    <li class="active ripple">#}
            {#                        <a href="#" class="nav-header"><span class="fa-cogs fa"></span>#}
            {#                            Login sistema#}
            {#                            <span class="fa-angle-right fa right-arrow text-right"></span>#}
            {#                        </a>#}
            {#                    </li>#}
            {#                {% else %}#}
            {#                    <li class="active ripple">#}
            {#                        <a href="#" class="nav-header"><span#}
            {#                                class="fa-dashboard fa"></span>#}
            {#                            Dashboard#}
            {#                            <span class="fa-angle-right fa right-arrow text-right"></span>#}
            {#                        </a>#}
            {#                    </li>#}
            {#                {% endif %}#}
            {#                {% if user.is_authenticated %}#}
            {#                    <li class="ripple">#}
            {#                        <a class="tree-toggle nav-header">#}
            {#                            <span class="fa-battery-half fa"></span>Movimento Associativo#}
            {#                            <ul class="nav nav-list tree">#}
{#            <li><a href="{% url 'subscription:quickregister' %}">Inscrição Rápida</a></li>#}

            <li role="presentation" class="active">
                <a href="#tabs-demo7-area1" id="tabs-demo6-1" role="tab" data-toggle="tab"
                   aria-expanded="false">Dados Pessoais</a>
            </li>
            <li role="presentation" class="">
                <a href="#tabs-demo7-area2" id="tabs-demo6-2" role="tab" data-toggle="tab"
                   aria-expanded="false">Morada</a>
            </li>
            <li role="presentation" class="">
                <a href="#tabs-demo7-area3" id="tabs-demo6-3" role="tab" data-toggle="tab" aria-expanded="false">Dados
                    Financeitos</a>
            </li>
            <li role="presentation" class="">
                <a href="#tabs-demo7-area4" id="tabs-demo6-4" role="tab" data-toggle="tab" aria-expanded="true">Conta-corrente</a>
            </li>
            <li role="presentation" class="">
                <a href="#tabs-demo7-area5" role="tab" id="tabs-demo6-5" data-toggle="tab" aria-expanded="true">Subscrições</a>
            </li>
            <li role="presentation" class="">
                <a href="#tabs-demo7-area6" role="tab" id="tabs-demo6-6" data-toggle="tab" aria-expanded="true">Informação
                    de Cartão</a>
            </li>
            <li role="presentation" class="">
                <a href="#tabs-demo7-area7" role="tab" id="tabs-demo6-7" data-toggle="tab" aria-expanded="true">Família</a>
            </li>
            <li role="presentation" class="">
                <a href="#tabs-demo7-area8" role="tab" id="tabs-demo6-8" data-toggle="tab"
                   aria-expanded="true">Notas</a>
            </li>
            <li role="presentation" class="">
                <a href="#tabs-demo7-area9" role="tab" id="tabs-demo6-9" data-toggle="tab"
                   aria-expanded="true">Documentos</a>
            </li>
            {#                            <li><a href="{% url 'memberprofiles:subscription:new' %}">Dados Pessoais</a></li>#}
            {#                            <li><a href="#">Morada</a></li>#}
            {#                            <li><a href="#">Dados Financeiros</a></li>#}
            {#                            <li><a href="#">Conta-Corrente</a></li>#}
            {#                            <li><a href="#">Subscrições</a></li>#}
            {#                            <li><a href="#">Informação de Cartão</a></li>#}
            {#                            <li><a href="#">Documentos</a></li>#}
            {#                            <li><a href="#">Notas</a></li>#}
            {#                        </ul>#}
            {#                            <span class="fa-angle-right fa right-arrow text-right"></span>#}
            {#                        </a>#}

            {#                        <ul class="nav nav-list tree">#}
            {##}
            {#                            <li><a href="#">Inscrição de Sócio</a></li>#}
            {#                            <li><a href="{% url 'memberprofiles:list' %}">Sócios</a></li>#}
            {#                            <li><a href="#">Alteração de Categoria</a></li>#}
            {#                            <li><a href="#">Alteração de Situação</a></li>#}
            {#                            <li><a href="#">Alteração Cobrador</a></li>#}
            {#                            <li><a href="#">2ª Via de Cartão</a></li>#}
            {#                            <li><a href="#">Dashboard</a></li>#}
            {#                            <li><a href="#">Consulta Movimento</a></li>#}
            {#                            <li><a href="#">Sócios Antigos</a></li>#}
            {#                        </ul>#}
            {#                    </li>#}

            {#                {% endif %}#}
        </ul>
    </div>
</div>
</div>

partners/subscriptions/templates/subscriptions/subscription_success.html
<form method="get" action="{% url 'memberprofiles:list' %}" class="form-horizontal">
    {% csrf_token %}
    <div class="col-md-8">
        <div class="panel form-element-padding">
            <div class="panel-heading">
                <h4>Ação</h4>
            </div>
            <div class="panel-body" style="padding-bottom:30px;">
                <div class="form-group">
                    <div class="col-sm-5">

                        <input type="submit" id="save" class="btn btn-primary" name="Save" value="Ok"
                               style="float:left;"/>
                    </div>
                </div>
                <div class="alert alert-success">
                    Ação realizada com sucesso!
                </div>
            </div>
        </div>
    </div>
</form>